-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 17:58:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `league` DEFAULT CHARACTER SET utf8 ;
drop database if exists `league`;
create database `league`;
USE `league` ;

-- -----------------------------------------------------
-- Table `team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team` ;

CREATE TABLE IF NOT EXISTS `team` (
  `team_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`team_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `player` ;

CREATE TABLE IF NOT EXISTS `player` (
  `player_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `position_id` INT NOT NULL,
  `rating` INT NOT NULL,
  PRIMARY KEY (`player_id`),
  CONSTRAINT `player_position_id`
    FOREIGN KEY (`position_id`)
    REFERENCES `position` (`position_id`)
)    
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_team` ;

CREATE TABLE IF NOT EXISTS `user_team` (
  `user_team_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `user_controlled` TINYINT NOT NULL DEFAULT 0,
  `rating` INT NOT NULL,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `team_id_idx` (`team_id` ASC) VISIBLE,
  PRIMARY KEY (`user_team_id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`),
  CONSTRAINT `team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `team` (`team_id`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `game` ;

CREATE TABLE IF NOT EXISTS `game` (
  `home_team_id` INT NOT NULL,
  `away_team_id` INT NOT NULL,
  `game_number` INT NOT NULL,
  `home_score` INT NULL,
  `away_score` INT NULL,
  `played` TINYINT NOT NULL,
  INDEX `home_team_id_idx` (`away_team_id` ASC, `home_team_id` ASC) VISIBLE,
  CONSTRAINT `home_team_id`
    FOREIGN KEY (`home_team_id`)
    REFERENCES `user_team` (`user_team_id`),
  CONSTRAINT `away_team_id`
    FOREIGN KEY (`away_team_id`)
    REFERENCES `user_team` (`user_team_id`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team_player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team_player` ;

CREATE TABLE IF NOT EXISTS `team_player` (
  `team_player_id` INT NOT NULL AUTO_INCREMENT,
  `user_team_id` INT NOT NULL,
  `player_id` INT NOT NULL,
  PRIMARY KEY (`team_player_id`),
  INDEX `user_team_id_idx` (`user_team_id` ASC) VISIBLE,
  INDEX `player_id_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `user_team_id`
    FOREIGN KEY (`user_team_id`)
    REFERENCES `user_team` (`user_team_id`),
  CONSTRAINT `player_id`
    FOREIGN KEY (`player_id`)
    REFERENCES `player` (`player_id`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record` ;

CREATE TABLE IF NOT EXISTS `record` (
  `user_team_id` INT NOT NULL,
  `win` INT NOT NULL,
  `loss` INT NOT NULL,
  CONSTRAINT `record_user_team_id`
    FOREIGN KEY (`user_team_id`)
    REFERENCES `user_team` (`user_team_id`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `position` ;

CREATE TABLE IF NOT EXISTS `position` (
  `position_id` INT NOT NULL AUTO_INCREMENT,
  `position` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`position_id`)
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
