-- MySQL Script generated by MySQL Workbench
-- Mon Nov  9 15:54:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `league` DEFAULT CHARACTER SET utf8 ;
USE `league` ;

-- -----------------------------------------------------
-- Table `mydb`.`division`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `division` ;

CREATE TABLE IF NOT EXISTS `division` (
  `division_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`division_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team` ;

CREATE TABLE IF NOT EXISTS `team` (
  `team_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `division_id` INT NOT NULL,
  PRIMARY KEY (`team_id`),
  INDEX `division_id_idx` (`division_id` ASC) VISIBLE,
  CONSTRAINT `team_division_id`
    FOREIGN KEY (`division_id`)
    REFERENCES `division` (`division_id`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `player` ;

CREATE TABLE IF NOT EXISTS `player` (
  `player_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_Name` VARCHAR(50) NOT NULL,
  `position` VARCHAR(50) NOT NULL,
  `rating` INT NOT NULL,
  `team_id` INT NULL,
  PRIMARY KEY (`player_id`),
  INDEX `team_id_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `player_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `team` (`team_id`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `manager` ;

CREATE TABLE IF NOT EXISTS `manager` (
  `manager_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `team_id` INT NULL,
  PRIMARY KEY (`manager_id`),
  INDEX `team_id_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `manager_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `team` (`team_id`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stadium`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stadium` ;

CREATE TABLE IF NOT EXISTS `stadium` (
  `stadium_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `capacity` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `team_id` INT NULL,
  PRIMARY KEY (`stadium_id`),
  INDEX `team_id_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `stadium_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `team` (`team_id`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `game` ;

CREATE TABLE IF NOT EXISTS `game` (
  `home_team_id` INT NOT NULL,
  `away_team_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `home_score` INT NULL,
  `away_score` INT NULL,
  INDEX `home_team_id_idx` (`home_team_id` ASC, `away_team_id` ASC) VISIBLE,
  CONSTRAINT `game_home_team_id`
    FOREIGN KEY (`home_team_id`)
    REFERENCES `team` (`team_id`),
  CONSTRAINT `game_away_team_id`
    FOREIGN KEY (`away_team_id`)
    REFERENCES `team` (`team_id`)
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
